"""Nicht-NULL-Felder

Revision ID: 1a25a9b2fc1b
Revises: 03c3b71600a8
Create Date: 2020-03-24 17:25:27.975145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a25a9b2fc1b'
down_revision = '03c3b71600a8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations_has_users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organizations_has_users', 'permission',
               existing_type=postgresql.ENUM('owner', 'admin', 'auditor', 'member', name='permssions'),
               nullable=False)
    op.alter_column('organizations_has_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations_has_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('organizations_has_users', 'permission',
               existing_type=postgresql.ENUM('owner', 'admin', 'auditor', 'member', name='permssions'),
               nullable=True)
    op.alter_column('organizations_has_users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
