"""Init

Revision ID: 0c83eae7e608
Revises: 
Create Date: 2020-03-29 16:52:08.550110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c83eae7e608'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(precision=53), nullable=True),
    sa.Column('latitude', sa.Float(precision=53), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['organizations.id'], name=op.f('fk_organizations_parent_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('auth_token', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('last_invite', sa.DateTime(), nullable=True),
    sa.Column('agreed_tos', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_token', name=op.f('uq_users_auth_token')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('organizations_has_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('permission', sa.Enum('owner', 'admin', 'auditor', 'member', name='permssions'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organizations_has_users_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organizations_has_users_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations_has_users'))
    )
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_phone_numbers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_numbers'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('minimum_required', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('is_available_on_workdays_day', sa.Boolean(), nullable=False),
    sa.Column('is_available_on_weekend_day', sa.Boolean(), nullable=False),
    sa.Column('is_available_on_workdays_night', sa.Boolean(), nullable=False),
    sa.Column('is_available_on_weekend_night', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_status_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status'))
    )
    op.create_table('calendar_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_has_user_id', sa.Integer(), nullable=True),
    sa.Column('calendar_entry_status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_entry_status_id'], ['status.id'], name=op.f('fk_calendar_entry_calendar_entry_status_id_status')),
    sa.ForeignKeyConstraint(['organization_has_user_id'], ['organizations_has_users.id'], name=op.f('fk_calendar_entry_organization_has_user_id_organizations_has_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_entry'))
    )
    op.create_table('organizations_has_users_has_roles',
    sa.Column('organizations_has_users_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizations_has_users_id'], ['organizations_has_users.id'], name=op.f('fk_organizations_has_users_has_roles_organizations_has_users_id_organizations_has_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_organizations_has_users_has_roles_role_id_roles')),
    sa.PrimaryKeyConstraint('organizations_has_users_id', 'role_id', name=op.f('pk_organizations_has_users_has_roles'))
    )
    op.create_table('users_has_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_has_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_has_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_users_has_roles'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_has_roles')
    op.drop_table('organizations_has_users_has_roles')
    op.drop_table('calendar_entry')
    op.drop_table('status')
    op.drop_table('roles')
    op.drop_table('phone_numbers')
    op.drop_table('organizations_has_users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
