"""User.email unique

Revision ID: 2399c3eb5146
Revises: 3c383fc6c05d
Create Date: 2020-03-26 13:20:10.032335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2399c3eb5146'
down_revision = '3c383fc6c05d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###
