"""User.is_validated

Revision ID: 4145ed002566
Revises: 0c83eae7e608
Create Date: 2020-03-30 12:18:42.588623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4145ed002566'
down_revision = '0c83eae7e608'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_validated', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_validated')
    # ### end Alembic commands ###
